# Generated by Django 4.1.3 on 2024-09-09 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fee",
            name="amount_paid",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
